version: "2.4"
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.18.0
    restart: unless-stopped
    ports:
      - 10000:10000
      - 10001:10001
    healthcheck:
      test: nc -z localhost 10000 || exit -1
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
